### ISSUE TITLE
It needs to be shipped

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/FingerprintSecureDrop#1]
@conorsch Hoping you can help me out. Code is ready, it just needs to be shipped to multiple DO servers 'round the :earth_americas:. If I could provision all of them with in one go that'd be awesome!
- [x] SF :bridge_at_night: 
- [x] New York :metro: 
- [x] London :tea:

**Comment by psivesely** [comment]
One server up in SF and https://github.com/freedomofpress/FingerprintSecureDrop/commit/eb655b8c04fe54ff8681900aef79b18d5a4ad36a merged.

**Comment by psivesely** [comment]
Servers up and running! Thanks @conorsch!

**Comment by conorsch** [comment]
:metal: :rocket: :guitar: :shipit:
