### ISSUE TITLE
Try each onion site more than once in the sorter

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/FingerprintSecureDrop#13]
there are ~7k+ onion sites in our lists, however we can reliably reach around ~2k with the sorter. we can probably increase this number by retrying onion sites that we don't get back 200 OK on the first GET request

**Comment by psivesely** [comment]
`sort_onions.py` is going to be refactored soon. I'll probably add a "chances" variable to allow for retrying of a site "chances" times. Two things to think about:
- Should the site be retried immediately, or should they be tried again after everything has been tried once? I'm leaning toward the latter.
- What about how to handle these "lesser reliable" sites on the crawler? Implement the same procedure for retry there?
