### ISSUE TITLE
Implement a robust test suite and a .travis.yml

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/FingerprintSecureDrop#28]
We should implement a robust test suite that covered all operations of the crawler and sorter. Then we can also take advantage of Travis for automatic integration tests instead of manually doing all testing. This issue is a WiP, the contents subject to change as we decide how we want to implement what tests. Feel free to edit @redshiftzero 
## Deployment
- [ ] Prevent regressions that may come with new tor versions by confirming that tor builds correctly after being patched and that the output to our log file looks as expected.
## Crawler
- [ ] Show how to take a screenshot with the post-GET function (`extra_fn`) you can specify/ test this functionality works as expected. Maybe confirm the screenshot PNG hash of a very static page is as expected.
- [ ] Manually raise some troublesome exceptions in the `extra_fn` and test they're handle correctly, produce tracebacks in logs, don't crash the crawler, etc..
- [ ] Show restart method works correctly (also a good time to test it for recovery from `_sketchy_exceptions`.
- [ ] Be able to work through a list of sites known to crash the crawler (previously) and show now that the crawler got that on lock.
## Database
- [ ] Sort the SecureDrop directory into _up-to-date_ (monitored) and _out-of-date_ (non-monitored) classes, then query the database for the onions that were sorted since the start of the test. Verify that the objects returned are the correct type and have sensible contents. Also verify that the SQL entries look like they should.
  - [ ] Following up on this, retrieve this data for a crawler run. Make sure the crawler can process the class data. After the crawler has without exception uploaded it's own results to the database, do some verification that the corresponding entries look sane.
    - [ ] Eventually follow up with a third step that makes sure the (not yet complete) feature generation/ feature schema related code integrates with the above.

**Comment by psivesely** [comment]
@redshiftzero What was the name of the feature computation testing library you mentioned was similar to https://github.com/HypothesisWorks/hypothesis-python? Also, noting Hypothesis here because it's a library I wanted to investigate using as part of our test suite(s).

**Comment by redshiftzero** [comment]
https://github.com/machinalis/featureforge !

**Comment by psivesely** [comment]
Hey @conorsch, do you think you'd have time in the coming days to write a .travis.yml for this repo?

**Comment by garrettr** [comment]
@fowlslegs Why don't you do it? It's easy!

**Comment by conorsch** [comment]
> Hey @conorsch, do you think you'd have time in the coming days to write a .travis.yml for this repo?

Not a chance!

> @fowlslegs Why don't you do it? It's easy!

:100: :volcano: :guitar:

**Comment by psivesely** [comment]
Closing because we have a decent test suite + Travis--still much room for improvement--but enough to close.
