### ISSUE TITLE
Make results of crawl immediately ready for analysis w/ go-knn

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/FingerprintSecureDrop#3]
In 52a6ab4e240f444d797698b1e6ec1847e0478269, I laid out a plan for the completion of work that needs to be done to finish the data collection mechanism such that data is immediately available for use by https://github.com/pylls/go-knn. The individual tasks to make this happen are as follows:
- [x] Define `sd_sample_ratio` in `config.ini`, and in the crawler do the following: (i) divide the not-sd class into `sd_sample_ratio` chunks and (ii) crawl the SD class once before each crawling each chunk of the not-sd class. This is following the practices of other researchers who collected numerous times more traces of the monitored class vs. the non-monitored class. Since our monitored class consists of just SDs, where each site has very little variation, we really want to hone in on it's specific variations, whereas, the non-monitored (i.e., not SDs) class being so large, we're just getting a general idea of the non-SD hidden service space, and since it's a much larger class and widely varied in terms of features, collecting a significant amount of traces shouldn't greatly change the average of the features of this class.
- [x] Following Wang et al. (WPES 2013, Appendix C) after the initial onload event of each site, we should (i) pause 5s to collect the traffic after the initial onload event, (ii) close the tab and start a new tab (or close TB if that's easier--depends on the capabilites tb-selenium has working reliably), (iii) close all open streams using `stem`.
- [x] During this whole process we will have `tor_cell_seq.log` open read only. Right before loading each site we will move our pointer in the file object up to the end of the file and after step (iii) from above we will read the to the end of the log and copy over the data as described in 52a6ab4e240f444d797698b1e6ec1847e0478269. We will not copy over tor cells that were part of client <-> IP or client <-> RP circuit construction to the  `<index>-<iteration>` file; we will only copy over the tor cell sequence data that was sent to and from the HS over the client <-> RP circuit. To slightly elaborate on how `<index>` is derived, during initialization of the crawler the crawler will store `self.sds_ord = len(self.sds)`, the order of the SD class. The SD class will have indices `0, ..., self.sds_ord - 1` and the the non-SD class will have indices `self.sds_ord, self.sds_ord + 1, ...` (or I may bump them up by one if go-knn is expecting indices to start at 1--TBD). The iteration should be pretty self explanatory.

**Comment by garrettr** [comment]
This all sounds pretty good.

My gut feeling says that you _might_ be doing too much to make the output of the crawler fit what go-knn wants as input. Personally, I would probably have the crawler dump a format that's as verbose as possible and allows easy introspection/verification. Then I would write a script to convert between that and what go-knn wants, creating a pipeline.

However, I haven't done nearly as much work on this as you have so I defer to your decision. 😁

**Comment by garrettr** [comment]
Github tip: :+1: for using a checklist. Feel free to describe the steps needed in more detail (e.g. split the big tasks into sublists of smaller, more granular tasks).

**Comment by psivesely** [comment]
While the `tor_cell_seq.log` would contain the full crawler dump, at the same time it would not be split into separate files for each site load. What's probably best is writing two files for each sequence, one with the complete information including circuit construction, and one in the space separated `<timestamp> <direction>` format that go-knn wants.
