### ISSUE TITLE
Better multi-user system support

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/FingerprintSecureDrop#51]
Multi-user machines are currently not well supported. To clarify, deploying to multi-user machines works just fine, but one has to re-run the playbook for each user, which is time and resource exhaustive compared to a _for-all-users-simultaneously_ deployment solution. Such a solution would require the following changes (and perhaps more):
- Download Tor and Tor Browser to `/usr/local/src/tbb` instead of `~/tbb`.
- Set environment vars for database access in `/etc/bash.bashrc` instead of `~/.bashrc`.
- Clone the repo itself to `/opt/FingerprintSecureDrop` instead of `~/FingerprintSecureDrop`.

The defaults in the `fpsd/{sorter.py,crawler.py,config.ini}` should be updated to reflect these changes. Thoughts @conorsch?

**Comment by conorsch** [comment]
Ha! Was _just_ about to open an issue to this effect. Happy to tackle this, let me toss up a very minor PR in the interim.

**Comment by psivesely** [comment]
@conorsch and I talked about this and noted we'd need to create a `list`-type var of usernames for which to create a `PGPASSFILE` in each of their home directories, since these require `0600` permissions. Then, in `/etc/bash.bashrc` we can set `export PGPASSFILE="${HOME}/.pgpass"`

**Comment by psivesely** [comment]
The other thing we discussed is making the Crawler a system (instead of user-instantiated) systemd service. We'd also want to create a special `fpsd` user (that has ownership of `/opt/FingerprintSecuredrop` with permissions set to `0644`), so that we don't run Tor Browser as root.

One more modification that would need to be made is `roles/crawler/files/relay.c.patch` would need to be modified to log to a new location (and the Crawler would need to be informed of that location s.t. it can read from it). Maybe `/var/log/tor/cell.log`.

**Comment by conorsch** [comment]
Most of the points discussed here are presented in #54, except for:

> The defaults in the `fpsd/{sorter.py,crawler.py,config.ini}` should be updated to reflect these changes.

Those haven't been added yet, so the service won't run as expected. Everything else is as discussed.
