### ISSUE TITLE
Re-name postgres-schemas dir to raw-tables

### ISSUE THREAD

**Issue by psivesely** [freedomofpress/FingerprintSecureDrop#73]

**Comment by conorsch** [comment]
This doesn't seem to affect anything at all, but if it's a more intuitive name, than I suppose it makes sense. @redshiftzero do you concur with the terminology proposed here?

**Comment by redshiftzero** [comment]
Well if we want to rename it then it should probably be called just `postgres-tables` or `database-tables` since after the merge of #57 that directory contains more than just create table scripts for the raw schema

**Comment by conorsch** [comment]
Fair point. Let's create intuitively named subdirectories in the `files/` dir so it's obvious what goes where. The tasks can be trivially updated to handle the new filepaths.

**Comment by psivesely** [comment]
Fixed in https://github.com/freedomofpress/fingerprint-securedrop/commit/33be2d7d550a222f9d4870f25dbaf4fda4e86b7c!
